### ISSUE TITLE
Add maintainers

### ISSUE THREAD

**Issue by davetcoleman** [ros-gbp/moveit_metapackages-release#1]
@isucan @mikeferguson Can myself and @130s be added to this repo? Thanks!

Per https://github.com/ros-planning/moveit_metapackages/issues/6

**Comment by mikeferguson** [comment]
you should have write it looks like -- there is a ros-planning-maintainers group and it has write on this (and basically every other moveit/nav) repo

**Comment by davetcoleman** [comment]
Ah you are correct - I checked the teams page. I was assuming because there was no "Settings" tab at the top I couldn't write to the repo, which only indicates admin access
